version: "2"
run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - gosec
    - ineffassign
    - misspell
    - unconvert
    - goconst
    - gocyclo
    - bodyclose
    - staticcheck
    - unused
    - errcheck

linters-settings:
  govet:
    enable-all: true
  gosec:
    severity: medium
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  revive:
    rules:
      - name: package-comments
        disabled: false
      - name: var-naming
        disabled: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
    - path: internal/logger/
      linters:
        - errcheck
  exclude:
    - "avoid meaningless package names"
  max-issues-per-linter: 50
  max-same-issues: 5