run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gofmt
    - govet
    - gosec
    - ineffassign
    - misspell
    - unconvert
    - goconst
    - gocyclo
    - bodyclose
    - gosimple
    - staticcheck
    - typecheck
    - unused
    - errcheck
    - revive

linters-settings:
  gofmt:
    simplify: true
  govet:
    enable-all: true
  gosec:
    severity: medium
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
    - path: internal/logger/
      linters:
        - errcheck
  max-issues-per-linter: 50
  max-same-issues: 5